spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jobfinder?useSSL=false&serverTimezone=UTC
    username: root
    password: BenTen20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: jobfinder
